development:
  sessions:
    default:
      uri: centro-dev
      options:
        safe: true
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: centro-test
      hosts:
        - localhost:27017
      options:
        safe: true
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        safe: true
  options:
    raise_not_found_error: false
