development:
  bucket: bucket-dev
  access_key_id: xxx
  secret_access_key: xxx

test:
  bucket: bucket-test
  access_key_id: xxx
  secret_access_key: xxx

production:
  bucket: ENV['S3_BUCKET']
  access_key_id: ENV['S3_ACCESS_KEY']
  secret_access_key: ENV['S3_SECRET_KEY']
